name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: ./build.sh
